### ISSUE TITLE
Add support for serial interface

### ISSUE THREAD

**Issue by osotechie** [febalci/pycrowipmodule#3]
Thanks for your awesome work on the pycrowipmodule. I was looking at the IP interface commands from AAP and realised they are the same commands used to interact with the system via serial.

How hard would it be to create a similar module or extend this module to use either IP or Serial to communicate with the system?

**Comment by febalci** [comment]
Dear @owendemooy, i created this component based on envisalink component from HA github page. I do not have any knowledge to handle serial commnuication on HA, but you might check out the envisalink component code on HA github page and if there is a serial communication code in there you can change the code accordingly. Sorry...
