### ISSUE TITLE
Initial help

### ISSUE THREAD

**Issue by t112013** [febalci/pycrowipmodule#5]
Hello, thanks for great work. But i have one question, how to set up ?

**Comment by febalci** [comment]
This is an API mainly used for the Home Assistant interface. You can find the details in this [forum post](https://community.home-assistant.io/t/custom-component-crow-runner-arrowhead-aap-8-16-alarm-ip-module/130588?u=febalci). If you want to use this API with some other smart home application, you have the develop the interface yourself. And sorry but there is no documentation about this API...

And also, as stated in the forum post, you have to upload a special firmware to your IP module.
